//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomBoy_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhPhong
    {
        public int id { get; set; }
        public int MaPhong { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
