//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomBoy_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDichVu()
        {
            this.ChiTietDichVus = new HashSet<ChiTietDichVu>();
        }
    
        public int MaPhieuDichVu { get; set; }
        public Nullable<int> MaDatPhong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public Nullable<int> MaDichVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDichVu> ChiTietDichVus { get; set; }
        public virtual DatPhong DatPhong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
